### PR TITLE
Enhancement/make tests run quicker and make them more atomic

### LINKED ISSUE #66: Make tests run quicker and make them more atomic
For now we have 1600 tests examples and it takes to long to run them after every change while developing or refactoring. The tests are over-engineered, with check for every element that is included or imported. 

We need to make them more atomic so we will test if class has correct includes without testing includes and their internal parameters.

### PR DESCRIPTION
**Pull request by Cosaquee**
fixes #66

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/coi-gov-pl/puppet-jboss/pull/76" target="_blank">ReviewNinja

**Comment by Cosaquee** [comment]
@coi-gov-pl/jboss-puppet-team please review : )

**Comment by therek** [comment]
:+1:

**Comment by cardil** [comment]
Wasn't I saying to cherry pick https://github.com/coi-gov-pl/puppet-jboss/commit/b3ba205be13df1daceab47a78ae62f461f37f7bf @Cosaquee? :smile:

**Comment by cardil** [comment]
Looks like an awesome job :+1:

**Comment by therek** [comment]
:+1:

**Pull request merged**
