### PR TITLE
Feature: Better acceptance tests!

### PR DESCRIPTION
**Pull request by cardil**
Acceptance test now are:

* working for all smoke tests:
 * init
 * securitydomain
 * module
 * jmsqueue
 * clientry
 * interface
 * jboss::as7
 * deploy
 * resourceadapter
* use actual smoke tests with helper method: `Testing::Acceptance::SmokeTestReader.smoke_pp :init`
* remove JBoss installation after test: `remove_jboss_installation('wildfly')`

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/coi-gov-pl/puppet-jboss/pull/72" target="_blank">ReviewNinja

**Comment by cardil** [comment]
Review please @coi-gov-pl/jboss-puppet-team

**Comment by Cosaquee** [comment]
:+1:

**Comment by therek** [comment]
:+1:

**Pull request merged**
