### PR TITLE
Bugfix/77 support for rake 11.0

### LINKED ISSUE #74: Support for rake v11.0
In the newest version of Rake there is no support for Ruby version 1.8. We need to still support  it so we need to download rake 10.5 in Gemfile for 1.8. In versions >1.8 we will use newest version of Rake.

### PR DESCRIPTION
**Pull request by Cosaquee**
Fixes #74

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/coi-gov-pl/puppet-jboss/pull/75" target="_blank">ReviewNinja

**Comment by cardil** [comment]
:+1: from me

**Comment by therek** [comment]
:+1:

**Comment by cardil** [comment]
I will merge it, because downed coveralls.io

**Pull request merged**
