### PR TITLE
Switch to Gitter.im chat instead of Slack

### PR DESCRIPTION
**Pull request by cardil**
### coi-gov-pl/puppet-jboss now has a Chat Room on Gitter

@cardil has just created a chat room. You can visit it here: [https://gitter.im/coi-gov-pl/puppet-jboss](https://gitter.im/coi-gov-pl/puppet-jboss?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/coi-gov-pl/puppet-jboss?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Gitter do not require user approval and user can sign in with Github accounts.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/coi-gov-pl/puppet-jboss/pull/69" target="_blank">ReviewNinja

**Comment by frodoslaw** [comment]
:+1:

**Comment by frodoslaw** [comment]
:-1:

**Comment by therek** [comment]
:+1:

**Pull request merged**
