### PR TITLE
Enhancement #10: Raising coverage to more then 80% and cover all Ruby source files

### PR DESCRIPTION
**Pull request by cardil**
This PR is huge but needs to be like this to actively fight back technical dept.

Good work mister @Cosaquee!

But, this needs to be explicitly tested - also manually on real machines, before merge!

### CODE REVIEW

**Comment by cardil** [comment]
This should fix enhancement #10

**Comment by Cosaquee** [comment]
:+1:  :dancers:

**Comment by cardil** [comment]
Tip for manual testing for @coi-gov-pl/jboss-puppet-team:

Puppet 3.7.4 - inside cointainer `docker run -it --rm devopsil/puppet:3.7.4`:
```bash
yum install -y tar git
puppet module install coi/jboss
rm -rf /etc/puppet/modules/jboss
cd /etc/puppet/modules
git clone https://github.com/coi-gov-pl/puppet-jboss.git jboss
cd jboss
git checkout feature/enh-10-cover-not-covered
```
and do some serious tests with `tests/*.pp` files

Do it also for Puppet 2.7.22 with cointainer `docker run -it --rm devopsil/puppet:2.7.22`

Run compliance suites for COI projects!

**Comment by Cosaquee** [comment]
I will run tests suites.

**Comment by cardil** [comment]
Unfortunately commit 8f06566 seems to not work as expected (should fix #50).

We need to write some spec test case for that to be explicitly tested

**Comment by cardil** [comment]
I like to confirm that those changes are 100% compatible with compliance suites for COI projects.

Todo before merge:

- [ ] write spec test to replicate #50 
- [ ] correct code change from 8f06566

After that reopen this PR

**Comment by cardil** [comment]
It should be okey now to be reviewed last time, before commit. Please approve @coi-gov-pl/jboss-puppet-team

**Comment by therek** [comment]
Looks good to me :+1:

**Comment by cardil** [comment]
Merge fixes #10

**Pull request merged**
